version: "3.9"

services:
  nginx:
    build: ./nginx
    image: nginx_app
    container_name: nginx_cont
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app
    container_name: django_cont
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - ".env"
    restart: always
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
